[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha"

[programs.localnet]
clearing_house = "7FUKtosmZd2Sj8gWY34Bmt9YwFw1Fe1PHc9bDfMYnZoK"
pyth = "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s"
