[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha"

[programs.localnet]
clearing_house = "7aCcNjnd5DLVPYi8npx9aquuKVrabeahtyKP3u7h65GJ"
pyth = "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s"
