[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha"
lint = "yarn prettify:fix && cargo fmt"
fulltest = 'cargo test && bash ./test-scripts/run-anchor-tests.sh'
watch_ts = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c bash ./test-scripts/single-anchor-test.sh'
watch_build = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c anchor build'
watch_cargo = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c cargo test -- --show-output'

[programs.localnet]
clearing_house = "DUZwKJKAk2C9S88BYvQzck1M1i5hySQjxB4zW6tJ29Nw"
pyth = "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s"

[[test.genesis]]
address = "DESVgJVGajEgKGXhb6XmqDHGz3VjdgP7rEVESBgxmroY"
program = "./deps/serum-dex/dex/target/deploy/serum_dex.so"
