[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./test-scripts/run-ts-mocha"

[programs.localnet]
clearing_house = "GCuH76fb1rXc7bjFXNcnNvWSekLgzpsnMbc1Ng4FsGSs"
pyth = "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s"
