name: SDK prerelease
on:
  push:
    branches:
      - master
    paths:
      - 'sdk/src/*'
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build sdk
        run: yarn
      - run: yarn build
      - name: Update package version
        run: npm version prerelease --preid=master
      - name: Git commit
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version);")
          git config user.name "GitHub Actions"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -a -m "sdk: release v$VERSION"
          git push origin HEAD
      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}